server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: Better-Iter Application

  profiles:
    group:
      "dev": "dev, auth, datasource, mail, redis, docs" # 개발 환경 프로파일
      "prod": "prod, auth, datasource, mail, redis, docs" # 운영 환경 프로파일
