spring:
  config:
    activate:
      on-profile: "aws"

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0B
      enabled: true

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        auto: false
        static: ${S3_REGION}
      s3:
        bucket: ${S3_BUCKET}

