name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout java code
        uses: actions/checkout@v3

      - name: Set up Jdk 11 ver
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: set yaml secret
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DATABASE_URL }}
          spring.datasource.username: ${{ secrets.DATABASE_USERNAME }}
          spring.datasource.password: ${{ secrets.DATABASE_PASSWORD }}

      - name: Grant execute Permission for gradlew
        run: chmod +x gradlew

      - name: Clean & Build with Gradle
        run: ./gradlew clean build -x test

      # Dockerhub Login
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # Docker buildx set up
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker build & push
      - name: Docker build & push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $ {{ secrets.DOCKER_USERNAME }}/clockbox:latest
        #          docker build -t better-iter .
        #          docker tag better-iter choidongkuen/better-iter:latest
        #          docker push ${{ secrets.DOCKER_USERNAME }}/better-iter:latest

        
        

